### ISSUE TITLE
Add method to check if a given path is a directory

### ISSUE THREAD

**Issue by Jason2605** [dictu-lang/Dictu#259]
# Summary
Similar to #257, there is no way to determine whether a given path is a directory or not. I propose adding an `isdir` method to the `Path` library.

**Comment by artorias111** [comment]
Hey! I'd like to try this. 
https://stackoverflow.com/questions/4553012/checking-if-a-file-is-a-directory-or-just-a-file
According to this, there's a way to add the S_ISREG() macro to check if the path points to a directory, can I try and implement this?

**Comment by Jason2605** [comment]
Thanks for the initial activity on the repo and for wanting to contribute, means a lot 😃

Note `S_ISREG()` will check if it's a regular file rather than a directory, `S_ISDIR()` will check if it's a directory! It would be worth looking into a similar version for windows, but for the time being i'm happy for you to crack on using the above macro.

I'll assign this ticket to you, and questions let me know!

**Comment by artorias111** [comment]
Hi!
I started off with editing the path.c file in Dictu/c/optionals/
by adding a isdir() function. However, when I try building it, I get an error message 

`‘isdir’ defined but not used [-Werror=unused-function]`

I'm a bit confused about which other file needs to be edited other than the path.c file, will keep looking in the meantime!

**Comment by Jason2605** [comment]
You will also need to register it within the module at the bottom of the file, see [here](https://github.com/dictu-lang/Dictu/blob/develop/c/optionals/path.c#L185-L189) for some examples!

**Comment by artorias111** [comment]
Oh alright got it, thanks!

**Comment by artorias111** [comment]
Hey! So I made the changes in path.c,
Should I add tests in the tests directory?
Also, should I add anything to the docs directory?

**Comment by artorias111** [comment]
Hey! Made changes to the files as you told. Could you check the pr and let me know if it's okay?

**Comment by Jason2605** [comment]
The PR was great, thank you very much!

Resolved as part of #269
