### ISSUE TITLE
Ability to sort lists

### ISSUE THREAD

**Issue by Jason2605** [dictu-lang/Dictu#264]
# Summary
Currently there is no method to sort lists. For this task we need to add `list.sort()` which would sort a list **in place**. There are methods in place for copying lists if the requirement is to not sort in place. Initially this can be a very simple implementation and only work on certain datatypes (initially numbers) and we can expand later if required. If a list contains something that is not a number, an error will be raised.

## Example
```
var x = [1, 5, 2, 3];
x.sort();
print(x); // [1, 2, 3, 5] 
```

**Comment by Apoorve73** [comment]
You need an in place sort to be applied, right?

**Comment by Jason2605** [comment]
Exactly yep! There are methods already present within Dictu to be able to copy lists (both shallow and deep) so to me it makes sense to have the .sort() functionality happen in place, and if a new list is needed, an explicit copy can be used.

**Comment by Apoorve73** [comment]
Awesome! Can you please tell, in which file the changes need to be made. I would love to contribute.

**Comment by Jason2605** [comment]
Of course! Many thanks for the initial activity :)

So, all of the list methods are defined within [lists.c](https://github.com/dictu-lang/Dictu/blob/develop/c/datatypes/lists.c). Within this file you'll quickly notice that the function signature is the same throughout in that it's `static Value <name>(VM *vm, int argCount, Value *args)` where <name> is obviously the function name. For this issue, we need to add a new function `sortList` with the same signature.

Once the function has been created, with the logic to sort the list, we need to make sure it's actually defined within the VMs listMethods table, this is done at the bottom of the file, within `declareListMethods` ([see here](https://github.com/dictu-lang/Dictu/blob/develop/c/datatypes/lists.c#L291-L303)).

If any of that isn't clear do let me know, or if you have other questions feel free to ask!

**Comment by Apoorve73** [comment]
Thank you for this wonderful explanation! I will start hunting over that ! :+1:

**Comment by NightShade256** [comment]
I would also love to work on this. I see that you have based Dictu off Crafting Interpreters.

**Comment by NightShade256** [comment]
Also I don't think a runtime error should be raised if the list contains other datatypes.

It is better for it to discard the error silently. But this is just my opinion.

**Comment by NightShade256** [comment]
I have successfully implemented the sorting algorithm, Quick Sort using the Hoare partition scheme.
Now checking for leaks, and polishing it.

![image](https://user-images.githubusercontent.com/25431369/94776769-f486d700-03df-11eb-86b5-4adfabf90a67.png)
