### ISSUE TITLE
Issue with str.split()

### ISSUE THREAD

**Issue by Jason2605** [dictu-lang/Dictu#280]
# Issue with str.split()
It seems passing an empty string to `str.split()` causes an infinite loop.
## Example
```
"test".split(""); // Infinite loop
"test".split("t"); // Works fine
```

**Comment by psymbio** [comment]
You can't have an empty separator.

https://stackoverflow.com/questions/20826788/str-split-giving-me-valueerror-empty-separator-for-a-sentence-in-the-for

**Comment by Jason2605** [comment]
You linked a post about `str.split` in python, yet this issue is about `str.split` in Dictu.

**Comment by vnksnkr** [comment]
Hi!can i look into this?

**Comment by Jason2605** [comment]
Of course @vnksnkr! I'll assign this to you. I can think of two possibilities can can go down to resolve this issue.
1. Similar to Python where an empty string is simply not allowed and would result in a runtime error
2. Attempting to split on an empty string would actually split it per character, like how JS does it

I'd probably opt for the latter myself since there's currently no functionality to split a string per letter without looping manually.
