### ISSUE TITLE
Create Alpine Docker image for Dictu

### ISSUE THREAD

**Issue by avinashupadhya99** [dictu-lang/Dictu#308]
Create an *alpine* based Docker image with dictu installed simillarly like the one created with *ubuntu* in [DictuUbuntuDockerfile](https://github.com/dictu-lang/Dictu/blob/develop/Docker/DictuUbuntuDockerfile).
Create it as `DictuAlpineDockerfile` under `Docker` directory and update the [Docker README.md](https://github.com/dictu-lang/Dictu/blob/develop/Docker/README.md) for the same.

Here is a failed attempt of mine-

```Dockerfile
FROM alpine

WORKDIR Dictu

RUN apk add make curl-dev gcc libc-dev --no-cache 

COPY . .

RUN make dictu DISABLE_HTTP=1

RUN cp dictu /usr/bin/ \
	&& rm -rf *

CMD ["dictu"]
```

There is an issue with the C compilation with this Dockerfile.

**Comment by Jason2605** [comment]
Thanks for this, i've created a pull request (#309) that should address the issues you were having. I think while we're at it actually, it may be a nice step to also run the tests as part of the docker container build process.

**Comment by avinashupadhya99** [comment]
What is the instruction for running the tests?

**Comment by Jason2605** [comment]
After we have built the interpreter we can run

```
RUN ./dictu tests/runTests.du
```

If the tests fail an exit code will be returned and the container won't build. This will be good to see cases where the interpreter can build fine, but the actual execution of Dictu code is not correct.
