### ISSUE TITLE
Add unicode support

### ISSUE THREAD

**Issue by Jason2605** [dictu-lang/Dictu#317]
# Add unicode support
## Summary
Currently within Dictu all string based activities are done on the number of bytes a string contains, rather than the number of characters, obviously this means some non-ascii characters will be dealt with wrong. We should change this to instead include support for unicode characters within the default strings.

## Example
```
Dictu Version: 0.11.0
>>> "Ā".len();
2
```

**Comment by Jason2605** [comment]
A potentially promising library: https://github.com/sheredom/utf8.h

**Comment by liz3** [comment]
<img width="798" alt="image" src="https://github.com/user-attachments/assets/b0af1e67-41d8-47ec-ad25-890eda103514">
👀

**Comment by Jason2605** [comment]
> <img alt="image" width="798" src="https://private-user-images.githubusercontent.com/21298625/367985790-b0af1e67-41d8-47ec-ad25-890eda103514.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NjE2MTEsIm5iZiI6MTcyNjU2MTMxMSwicGF0aCI6Ii8yMTI5ODYyNS8zNjc5ODU3OTAtYjBhZjFlNjctNDFkOC00N2VjLWFkMjUtODkwZWRhMTAzNTE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE3VDA4MjE1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4ZDNkNzViMmU5N2E5NzdjY2Q4MjhlZGQ5YmE1YzRkYzgzNzUyM2EyODI1MjkyNmU2MmNiNjM0M2Q5ZmEyZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JW9OZlW1OtQA0cklanySHujHV9hY35mSBKC3iMtBNT4"> 👀

:OOOOO omg exciting stuff!!!
