### ISSUE TITLE
Supports only f32?

### ISSUE THREAD

**Issue by Scientific-Guy** [dictu-lang/Dictu#403]
Does dictu supports only f32 or does f64 numbers too?

**Comment by Jason2605** [comment]
All numeric values in Dictu are a double (64 bit IEEE 754)

**Comment by Scientific-Guy** [comment]
And what is the maximum index of it?

**Comment by Jason2605** [comment]
It depends exactly what you mean by "index" (i'm assuming you mean maximum value). Theoretically the max value of a 64 bit double is 1.7E+308, however, in reality the mantissa of a IEEE 64 bit double is 52 bits so your range in practice is smaller (2^53-1 OR 9007199254740991).

I see you have experience with JS, it's the exact same situation in JS as it is in Dictu if that helps contextualise things a little more for you.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER

**Comment by Scientific-Guy** [comment]
Ahhhh. I understand. Does dictu supports numbers larger than the MAX_SAFE_INTEGER by rounding it off like js does.

**Comment by Scientific-Guy** [comment]
Thanks for the answer for the question.
