### ISSUE TITLE
Run through the test suite

### ISSUE THREAD

**Issue by Jason2605** [dictu-lang/Dictu#420]
# Test suite
## Summary
There are quite a few tests within the Dictu repository, but it would be great if we could run through them and add as many tests as possible to cover any edge cases that are missing. May be worth looking into some sort of fuzzer here as well.

If any issues are found it would be great if they could be raised individually here as issues!

**Comment by LEO1612D** [comment]
Hi, I can contribute in this issue.

**Comment by Jason2605** [comment]
Perfect, thank you!
