### ISSUE TITLE
List unpacking

### ISSUE THREAD

**Issue by Jason2605** [dictu-lang/Dictu#421]
# List unpacking
## Summary
List unpacking is only working when we are declaring the variables. It should also work with previously defined variables. Need to investigate further into why this is happening, will drop more info here as I find it.

#### Example
![image](https://user-images.githubusercontent.com/20248039/135511756-e4697d1e-c90d-4ec8-a2a3-4155ad811737.png)

**Comment by Fly-Style** [comment]
I'd like to pick it.

**Comment by Jason2605** [comment]
@Fly-Style awesome, assigned this to you!

**Comment by Jason2605** [comment]
@Fly-Style Going to remove your assignment as it's been just over half a year now.

**Comment by MannarAmuthan** [comment]
Hi @Jason2605,   Could you provide the example for a proper **list unpacking**?

**Comment by Jason2605** [comment]
@MannarAmuthan There is an example in the screenshot in how it should work, but doesn't, it currently works when you declare a variable but not when you set a variable.

Example:

```
// Fine
var [x, y] = [1, 2];
print(x); // 1
print(y); // 2

// Issues
var x, y;
[x, y] = [1, 2]; // Invalid assignment target
```

**Comment by MannarAmuthan** [comment]
Hi Could you assign this to me?, I'd like to pick it.

**Comment by MannarAmuthan** [comment]
Hi , Which one is correct syntax for unpacking already declared variables x,y?

var x,y;
[x, y] = [1, 2]; 
(or)
var x,y;
x,y=[1,2];

**Comment by Jason2605** [comment]
The first option is what we should have available to us for list unpacking

```
var x,y;
[x, y] = [1, 2];
```

**Comment by MannarAmuthan** [comment]
Raised pull request for fix: https://github.com/dictu-lang/Dictu/pull/546

**Comment by MannarAmuthan** [comment]
Found some issues , will fix it
