### ISSUE TITLE
Github templates

### ISSUE THREAD

**Issue by Jason2605** [dictu-lang/Dictu#422]
# Github templates
## Summary
Setup github templates for both issues and pull requests so that issues and pull requests follow a certain format including all the relevant information we'd need.

Unsure on what the templates should contain at the moment, but happy for others to propose ideas. Will also check similar repositories for inspiration.

**Comment by MidouWebDev** [comment]
@Jason2605 can you assign me ?
I want to work on it.

**Comment by Jason2605** [comment]
Done, thank you @MidouWebDev

**Comment by MidouWebDev** [comment]
@Jason2605 do you want these templates to be markdown based or the new github issues and PRs templates (.yml) ?

**Comment by Jason2605** [comment]
@MidouWebDev I'm open to either format really, just as long as they show up when creating issues and pull requests!

**Comment by MidouWebDev** [comment]
@Jason2605 Ok.

**Comment by MidouWebDev** [comment]
@Jason2605 I will be creating the feature template soon
