### ISSUE TITLE
Unit test module

### ISSUE THREAD

**Issue by Jason2605** [dictu-lang/Dictu#431]
# UnitTest
## Summary
`UnitTest` would be a module that would allow users to create unit tests with ease. Testing code is a core component of a developers daily life, so we should strive to make testing Dictu code as easy as possible. Currently there is `assert` but that causes all execution to stop on the first failed assertion. We would need a way to carry out tests in a manner that can fail (logically), while still allowing execution to continue.

To be added to, but things such as:
- Assertions (assertTrue / assertFalse / assertEquals / assertError / assertSuccess) etc should be added.
- Ability to mock objects
- Ability to spy on objects (maybe in the future?)
- And more..

**Comment by classerase** [comment]
could this actually be programmed in dictu?

**Comment by Jason2605** [comment]
It could yeah, @classerase

**Comment by classerase** [comment]
where would this be added?

**Comment by Jason2605** [comment]
It would end up being much list the methods added to the List data type that are written in Dictu - [see here](https://github.com/dictu-lang/Dictu/tree/develop/src/vm/datatypes/lists) - except that since it's a module, you would place it within the optionals directory.

**Comment by classerase** [comment]
oh i see, and would that be it for the PR?

**Comment by Jason2605** [comment]
> oh i see, and would that be it for the PR?

I'm not quite sure what you mean "would that be it", would what be it sorry? The points highlighted in the initial issue are definitely welcome additions - i'm sure this module will grow over time though!

**Comment by classerase** [comment]
after implementing the dictu file in optionals, would i have to do anything on the "C side" of the language

**Comment by Jason2605** [comment]
Oh I see what you're saying sorry - yes you would. Much like in the [lists.c file](https://github.com/dictu-lang/Dictu/blob/develop/src/vm/datatypes/lists/lists.c#L413) you would need to interpret the source in a function called something like `createUnitTestModule` which returns the module (see [datetime.c](https://github.com/dictu-lang/Dictu/blob/develop/src/optionals/datetime.c#L157) as an example). Finally you'd need to include it in the [optionals.c array of modules](https://github.com/dictu-lang/Dictu/blob/develop/src/optionals/optionals.c#L3-L19)

**Comment by classerase** [comment]
Ok, that helps a lot. One more thing, would i need to make a wrapper for the functions im implementing in dictu? If not, how would I add them in `createUnitTestModule`?

**Comment by Jason2605** [comment]
Lets say you create this file, `unitTest.du`

```
def assertTrue(condition) {
    // Ignore the implementation for now, thats not super important
    return true;
}
```

Then in `optionals/unitTest/unitTest.c` you would have

```
#include "unitTest-source.h"

ObjModule *createUnitTestModule(DictuVM *vm) {
    dictuInterpret(vm, "UnitTest", DICTU_UNIT_TEST_SOURCE);

    Value UnitTest;
    tableGet(&vm->modules, copyString(vm, "UnitTest", 8), &UnitTest);

    return AS_MODULE(UnitTest);
}
```

This is untested (and written in the github editor) so there may be a few hiccups but hopefully it should give you the idea

**Comment by classerase** [comment]
and `unitTest.du` is also in `optionals/unitTest/`?

**Comment by Jason2605** [comment]
It would be yep. This file would end up getting "built" into `unitTest-source.c`.
See here:
- https://github.com/dictu-lang/Dictu/blob/develop/src/vm/datatypes/lists/list-source.h
- https://github.com/dictu-lang/Dictu/blob/develop/src/vm/datatypes/lists/list.du

Script that currently "builds" the datatypes source (you can do it by hand if you so wish for this PR)

- https://github.com/dictu-lang/Dictu/blob/develop/src/vm/datatypes/generate.du

**Comment by classerase** [comment]
ok cool. does dictu have a class representing errors?

**Comment by Jason2605** [comment]
It has a Result type yeah, see here: https://dictu-lang.com/docs/error-handling A result can either be in a Success state or an Error state

**Comment by classerase** [comment]
Looks good. I'll implement the assertions tomorrow, gotta research more on mocking objects.

**Comment by WillDaSilva** [comment]
I moved `generate.du` into a top-level scripts dir: https://github.com/WillDaSilva/Dictu/commit/c28c37c3d13dd77e31a164146bafb7d417557e49

Feel free to cherry-pick the changes.

**Comment by WillDaSilva** [comment]
Commenting here too keep the discussion about using Dictu source code in the standard library in one place.

@Jason2605 I have tried the general approach outlined here with two `createFuncToolsModule` definitions:

```
ObjModule *createFuncToolsModule(DictuVM *vm) {
    dictuInterpret(vm, "FuncTools", DICTU_FUNCTOOLS_SOURCE);

    Value FuncTools;
    tableGet(&vm->modules, copyString(vm, "FuncTools", 9), &FuncTools);

    return AS_MODULE(FuncTools);
}
```

```
ObjModule* createFuncToolsModule(DictuVM *vm) {
    ObjString* name = copyString(vm, "FuncTools", 9);
    push(vm, OBJ_VAL(name));

    ObjModule *module = newModule(vm, name);
    push(vm, OBJ_VAL(module));

    dictuInterpret(vm, "FuncTools", DICTU_FUNCTOOLS_SOURCE);

    pop(vm);
    pop(vm);
    return module;
}
```

Both approaches result in a segfault inside the nested call to `dictuInterpret`. `dictuInterpret` is first called to evaluate the import statement `import FuncTools;`, and then called again within `createFuncToolsModule`. I recall you told me that the vm is not reentrant, so I'm not sure that this general approach will work.

Maybe instead we can do something similar to whatever the import statement does when it imports a module defined in a `.du` file, except instead of reading a `.du` file in we use `DICTU_*_SOURCE`.

**Comment by Jason2605** [comment]
@WillDaSilva Very good point, this will probably need some more investigation to ensure that the source can be interpreted correctly without segfault. I think you're right in that it will stem from the VM not being re-enterant but definitely worth looking into further and seeing what is the cause.

We can try to look at alternatives, however, imports are too handled at compile time - the issue here is that we are trying to execute Dictu source code at runtime, so the pointers within the VMs `run()` are becoming out of sync. May be a tricky issue to solve

**Comment by WillDaSilva** [comment]
> imports are too handled at compile time

How does `import "some/file.du" as SomeModule;` work then?

**Comment by Jason2605** [comment]
Good point, especially since there are opcodes dealing with importing 😆. I'm talking rubbish there sorry, will definitely need to do some more investigation into this.
