### ISSUE TITLE
[FEATURE] Examples should be run in CI

### ISSUE THREAD

**Issue by WillDaSilva** [dictu-lang/Dictu#447]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Updates could create regressions that break examples, yet pass all of the tests.

### Describe the solution you'd like

While improving the tests should be the primary method of avoiding this issue, it would also be simple to execute all of the examples to see if they crash with a runtime error.

This could be done with a `scripts/runExamples.du` script. While addressing this issue, it might also make sense to move `tests/runTests.du` to `scripts/runTests.sh`.

**Comment by Jason2605** [comment]
Point taken, simple enough to add. For the case of the examples I'm happy for this to be ran on a single OS instance rather than a matrix of OSs like the tests - probably the latest version of Ubuntu.
