### ISSUE TITLE
[FEATURE] Method annotations

### ISSUE THREAD

**Issue by Jason2605** [dictu-lang/Dictu#464]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

As of #417 annotations have been added to Dictu, however, they are only currently available on classes. This feature should be extended so that they are also available on methods within a class.

**Comment by briandowns** [comment]
I was giving this some thought over the last few days as I've been working on a simple ORM in Dictu. I like that the annotations are a dict on the class and easily accessible. I had a thought that we could have 3 keys in that dict that are always present: "class", "methods", "fields". They'd always be there for reference for length checks, etc.

Practical example inspired by my test code:

```cs
{
    "class": {
        "Table": "USERS"
    },
    "methods": {},
    "fields": {
        "PrimaryKey": "",
        "AutoIncrement": "",
        "Name": "ID"
    }
}
```
