### ISSUE TITLE
[FEATURE] use 'not' instead of '!' for logical negation

### ISSUE THREAD

**Issue by gvwilson** [dictu-lang/Dictu#490]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Dictu uses `and` and `or` for logical operators; using `not` instead of `!` is more consistent, so remove support for `!` as a synonym for `not` (which has already been added).
### Describe the solution you'd like

1. Minor change to the scanner and compiler (I can do this).
2. Equally minor changes to existing Dictu library, tests, and examples (I can do this).

**Comment by Jason2605** [comment]
Yeah I toyed with this a while ago. Having both obviously isn't great, but at the time my thinking was `!` for "not" made sense as it is similar to `!=`. Having a `not` keyword along with `!=` always was a bit odd for me when working with Python.

Happy to discuss though!

**Comment by gvwilson** [comment]
I guess it's a question of which similarity is more intuitive for new users: `!` as in `!=` or `not` as in `and` and `or`. (I really wish `≠`, `≤`, and `≥` were standard keyboard symbols and part of 7-bit ASCII, but that ship sailed about fifty years ago…)

**Comment by Jason2605** [comment]
Yeah, it's an interesting dilemma and one I'm not sure I know the answer to yet. It also depends what you define "new user" as, if it's someone completely green to programming it's probably less of an issue, but if someone has experience in pretty much any c-like language you're using `!` for `not`.

Appreciate the PR regardless though!

**Comment by Jason2605** [comment]
Since `not` is actually the operator listed in the docs and not `!` I'll probably go ahead with this! Quite bad I hadn't noticed there wasn't both options in the docs previously 😰
