### ISSUE TITLE
[FEATURE] - Chat

### ISSUE THREAD

**Issue by briandowns** [dictu-lang/Dictu#498]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Do you folks have any means of chat or collaboration outside of Github?

**Comment by Jason2605** [comment]
Being brutally honest, the repo has been fairly inactive (outside myself) so there hasn't really been a need up until now ;(

Previously when I had a couple of collaborators it was done either via Email or via Discord

**Comment by briandowns** [comment]
I know how that goes. I have a couple repos that ebb and flow in terms of activity. Cool. I'll just add issues with questions when necessary. Thanks!
