### ISSUE TITLE
[BUG] - Not Building on FreeBSD

### ISSUE THREAD

**Issue by briandowns** [dictu-lang/Dictu#506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

cmake is unable to find `curl.h`.

### Expected Behavior

Builds successfully.

### Steps To Reproduce

Build steps from `README.md`.

**Comment by briandowns** [comment]
I'm not as familiar with `cmake` as I am `make` so I'm searching through to find where I can point `cmake` to find the `curl.h` file.

**Comment by Jason2605** [comment]
I don’t have much FreeBSD experience unfortunately so I’m unsure on the package manager it uses, but if you wish to use the HTTP library you’ll need to install cURL via the package manager. If you want to compile without cURL (and therefore the HTTP library) you can disable HTTP with the DISABLE_HTTP flag: https://github.com/dictu-lang/Dictu#compiling-without-http

**Comment by briandowns** [comment]
I just need to figure out how to point cmake to where the curl header is.

**Comment by Jason2605** [comment]
Oh I see what you're saying. Yeah there isn't currently a way through CMAKE to use a custom cURL header file, it's expecting it to already be there to be linked dynamically: https://github.com/dictu-lang/Dictu/blob/develop/src/optionals/http.h#L5

**Comment by briandowns** [comment]
Well, I finally got a chance to look back at this and have things working. The following lines need to be ran. I'll update the README with a section for FreeBSD if that's ok.

```
export CPATH=/usr/local/include
export LIBRARY_PATH=/usr/local/lib
export LD_LIBRARY_PATH=/usr/local/lib
```
