### ISSUE TITLE
[FEATURE] - syscall module

### ISSUE THREAD

**Issue by briandowns** [dictu-lang/Dictu#507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

It'd be nice to expose raw syscalls through the language. This would allow for the building of modules dependent on calling system calls directly.

**Comment by Jason2605** [comment]
Interesting, exposing syscalls in a high level language with it's own library isn't something I've seen before. I know Python for example allows you to run syscalls through libc via ctypes (essentially an FFI), do you think this would (eventually) be the best route for it?

**Comment by briandowns** [comment]
I was looking to have something like: https://pkg.go.dev/syscall#Syscall to be able to do something like: https://github.com/briandowns/jail

**Comment by briandowns** [comment]
Not necessary after further review. Closing.
