### ISSUE TITLE
[FEATURE] - Introduce a "database" module

### ISSUE THREAD

**Issue by briandowns** [dictu-lang/Dictu#509]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

The introduction of a database module could be useful to abstract database functionality and allow the use of multiple database backends.

### Describe the solution you'd like

A database class that has the expected methods of `execute` and `close` but when initialized, a type and config is passed in. 

Delusional example code to stimulate ideas:

```c
#define SQLITE3_DRIVER  1
#define MYSQL_DRIVER    2
#define POSTGRES_DRIVER 3
#define REDIS_DRIVER    4

static int driver;

typedef struct {
    union {
        sqlite3 *db;
        redisContext *db;
    };
    bool open;
} Database;
```

```c
ObjModule *createDatabaseModuleDictuVM *vm) {
    ObjString *name = copyString(vm, "database", 8);
    push(vm, OBJ_VAL(name));
    ObjModule *module = newPackage(vm, name);
    push(vm, OBJ_VAL(package));

    defineNativeProperty(vm, &module->values, "SQLITE3", NUMBER_VAL(SQLITE3_DRIVER));
    defineNativeProperty(vm, &module->values, "MYSQL", NUMBER_VAL(MYSQL_DRIVER));
    defineNativeProperty(vm, &module->values, "POSTGRES", NUMBER_VAL(POSTGRES_DRIVER));
    defineNativeProperty(vm, &module->values, "REDIS", NUMBER_VAL(REDIS_DRIVER));
    
    /**
     * Define database methods
     */
    defineNative(vm, &module->values, "init", initDB);
    defineNative(vm, &module->values, "connect", connectDB);

    pop(vm);
    pop(vm);

    return module;
}
```

```cs
database.init(database.SQLITE3);
var db = database.connect(data_dir).unwrap();
```

**Comment by Jason2605** [comment]
This is an interesting concept but probably a little _too_ feature rich to be part of the actual interpreter. We would end up needing to support many different database APIs for this to be of any use. I think it's definitely a nice package to have, especially when an FFI is available, but something that would probably be available via a package manager download.

Thoughts?

**Comment by briandowns** [comment]
Yeah, package manager seems like it's it's the correct way to go.
