### ISSUE TITLE
[FEATURE] Extend the HTTP module

### ISSUE THREAD

**Issue by Jason2605** [dictu-lang/Dictu#511]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I think it would be a nice idea to extend the HTTP module. Now we have support to write things in Dictu we could even write a lot of it within the language itself.

So a bit of context, currently the response on a HTTP request is a dictionary with related data - I think it would be better if we instead returned a Response object. This object can then contain further helper methods (such as .json() for example) to make dealing with HTTP responses much more friendly.

### Describe the solution you'd like

To begin with a new Response object for HTTP responses.
More HTTP verb methods

**Comment by briandowns** [comment]
Awesome idea!
