### ISSUE TITLE
[BUG] Compiler segmentation fault on input

### ISSUE THREAD

**Issue by tri2820** [dictu-lang/Dictu#526]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

The compiler correctly shows the syntax errors for this file but then gives segmentation fault.
[crash.du](https://gist.github.com/tri2820/07e619568ece8e6cfe3415866f43bb25)

### Expected Behavior

The compiler shows the errors and exits gracefully.

### Steps To Reproduce

run `dictu crash.du`

### Anything else?

gdb traces

![Screenshot from 2022-05-21 03-04-36](https://user-images.githubusercontent.com/22129923/169578958-13196885-d849-4aff-8b66-2d34e6952cbf.png)

**Comment by Jason2605** [comment]
Thanks for reporting the issue and providing reproducible steps!

**Comment by Jason2605** [comment]
This no longer segfaults on the latest develop version
