### ISSUE TITLE
[FEATURE] - Extend System Module Properties with Additional uname Fields

### ISSUE THREAD

**Issue by briandowns** [dictu-lang/Dictu#533]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Currently the System module provides a `platform` variable from uname(3) but it'd be nice to have the rest of the fields exposed in Dictu from that struct. 

I was curious the thoughts around how that data should be returned? Additional fields just like `System.properties` or maybe a function call that returns all of the values?

**Comment by Jason2605** [comment]
We could do it a couple of ways I guess, we could have them all defined within a dictionary on a property within the `System` module, or we could introduce it as a function call, again which could return a dict. I would probably go with the function call, means we don't need to have this dictionary hanging about in memory whenever the `System` module gets imported
