### ISSUE TITLE
[FEATURE] - HTTP Client Always Follows Redirects

### ISSUE THREAD

**Issue by briandowns** [dictu-lang/Dictu#564]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Most HTTP clients in languages will follow redirects however provide a means of telling the client not to do so.

### Describe the solution you'd like

Add a field to the http client options indicating that the client it is to not follow redirects.

**Comment by Jason2605** [comment]
In my testing it seems it's currently defaulting to the opposite (as in not following redirects). I wonder if this is something we should default to true throughout the library and allow people to opt-out with the client options

**Comment by briandowns** [comment]
Yes, sorry. I didn't word that very well. Yes, that's the current behavior. I'll submit a PR this evening.
