### ISSUE TITLE
[FEATURE] - Provide Ability to Write Downloaded Data to a File

### ISSUE THREAD

**Issue by briandowns** [dictu-lang/Dictu#567]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

There doesn't appear to be any way of writing the content retrieved from an HTTP call to a file. I don't have any good suggestions on how to implement this as there are a number of ways to examine. Open to suggestions.

**Comment by Jason2605** [comment]
Are you talking about some sort of stream interface for large files or?

**Comment by briandowns** [comment]
Yes, for instance downloading tars, or other files of interest.

**Comment by briandowns** [comment]
I've been giving this some thought and I haven't come up with anything concrete. I wanted to come up with something that wouldn't break the current API but that seems impossible.

Option 1:
Add an optional argument to argument to the `get` methods of a file path and on existence, a function is given to curl to write the received data to that file.

Option 2:
Introduce a new type to Dictu called `Bytes` and change the HTTP.Response.content field to be of this type. The caller then chooses what to do with the bytes. We could also add `b'all of the bytes';` style 

Option 3:
Add a method to the module and on the client to specifically download files.

Option 4:
Another much better option.

**Comment by briandowns** [comment]
I was hoping to work on this issue next week during my company's hackweek. Wanted to get your (@Jason2605 ) thoughts on how you want to see this implemented. Thanks in advance!

**Comment by Jason2605** [comment]
I think option 2 is probably the route I would go with introducing a new bytes type, as this is something that will need doing eventually anyways. Once we have a dedicated bytes type we can default the string type to handle unicode chars to bring the string type into the modern era. Probably the most work involved in this option, but I think it's the way to go!

**Comment by briandowns** [comment]
Thank you for the feedback! Will get started on this next week.

**Comment by Jason2605** [comment]
Much appreciated, thank you

**Comment by briandowns** [comment]
I found a workout around for this that will not require any new types or adjustments to the HTTP module. I'll submit the PR by tomorrow night. This will open the door to so much. :D
