### ISSUE TITLE
[FEATURE] - Flags Module Proposal

### ISSUE THREAD

**Issue by briandowns** [dictu-lang/Dictu#570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Dictu doesn't currently have the ability to parse flags/arguments provided to a script. This is a proposal for how that API would look. 

### Describe the solution you'd like

The import:
```cs
import Flags;
```

Values would be defined by calling functions defined in the `Flags` module. Each of those functions would take the short version of the flag, the long version, or blank for either (not both), and a description.

```cs
const host = Flags.string("h", "host", "host address");
const port = Flags.number("p", "port", "port for the server to listen on");
const secure = Flags.bool("s", "", "listen via ssl/tls");
const users = Flags.list("u", "users", "active system users");
Flags.parse();
```

```sh
./script.du -h "127.0.0.1" -p 8888 -s -u briandowns,Jason2605
```

The `const` values can be used as any normal values would be.

```cs
print(host); // "127.0.0.1"
print(port); // 8888
print(secure); // true
print(users); // ["briandowns", "Jason2605"]
```

As a phase 2 portion of the implementation, another function should be added to the `Flags` module called `usage` which will return a formatted "usage" / "help" menu based on the given flags.

```sh
Usage: <SCRIPT_NAME> 
Options:
    h, host           host address
    p, port            port for the server to listen on
    s                     listen via ssl/tls
    u, users          active system users
```

Hoping to bother you (@Jason2605 ) for some feedback.

**Comment by Jason2605** [comment]
I wouldn't mind seeing something like this within the Dictu stdlib, it reminds me a lot of Pythons argparse (https://docs.python.org/3/library/argparse.html) library. Off the top of my head I'm unsure how we would assign to those variables and then mutate them once the `.parse()` function runs, we may have to return something like a dictionary when running `.parse()` there.

My thinking for this is it will probably be easier to write something like this within Dictu (although I generally say to write stdlib items in C for it's speed, but in this case it shouldn't matter too much) so we might have something like:

```
from Flags import Flags;

const flags = Flags();
flags.string("h", "host", "host address");
flags.number("p", "port", "port for the server to listen on");
flags.bool("s", "", "listen via ssl/tls");
flags.list("u", "users", "active system users");
flags.parse(); // {"..." : ...}
```

And potentially the `Flags` name - I do quite like `ArgParse` but i'm not too bothered on that one really

**Comment by briandowns** [comment]
Lemme play around a little more and come up with another iteration on this. Thank you for the feedback!

**Comment by briandowns** [comment]
Proposal 2: 

```cs
var parser = Parser("program_name", "description", "custom usage");

// Parser.AddX(short: string, long: string, desc: string, required: bool, metavar: string)
parser.addString("-h", "--host", "host address", true, "host");
parser.addNumber("-p", "--port", "port for the server to listen on", true);
parser.addBool("-s", "", "listen via ssl/tls", false);
parser.addList("-u", "--users", "active system users", false, "users");

// dict keys are determined by the following:
// 1. a given metavar name. or..
// 2. the long form flag. or...
// 3. the short form flag.
const args = parser.parse();

print(args["host"]); // 127.0.0.1
print(args["port"]); // 8888
print(args["s"]); // true
print(args["users"]); // ["briandowns", "Jason2605"]
```

Open to some feedback on this iteration @Jason2605 .

**Comment by Jason2605** [comment]
This one looks good to me!

**Comment by briandowns** [comment]
Awesome. Gonna start fleshing out the code but please let me know if you want anything in this changed. Happy to meet your expectations.

**Comment by Jason2605** [comment]
This looks really good to me so far! Let me know if there's anything I can help with
