### ISSUE TITLE
[FEATURE] - Thoughts on the Removal of Semicolons from the Grammar

### ISSUE THREAD

**Issue by briandowns** [dictu-lang/Dictu#589]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Wren and other similar languages removed the need for the semicolon. Wanted to get thoughts on removing it from Dictu.

**Comment by Jason2605** [comment]
I think for now we will leave it in, it keeps the compiler a little easier rather than needing some sort of logic to either determine where a semi-colon should go or something more a bit more invasive like reliant on white-space

**Comment by briandowns** [comment]
I was going through a lot of Wren code and figured I'd ask. Thanks!
