### ISSUE TITLE
[BUG] - Sometimes methods with annotations aren't processed correctly

### ISSUE THREAD

**Issue by briandowns** [dictu-lang/Dictu#590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I haven't been able to determine a cause yet but on Linux systems, occasionally a method with annotations will complete parsing incorrectly. The `__annotatedMethod` placeholder isn't always replaced with the method name.

**Comment by Jason2605** [comment]
This is interesting, do you have an example source file I can try?

**Comment by Jason2605** [comment]
It's all good! Yeah, if you can piece together something where you can reproduce that would be incredibly helpful, thank you

**Comment by briandowns** [comment]
The relevant code is the `last` method in this class.

```cs
@Controller("/api/v1/releases")
class Releases {
    private dataStore;

    init(dataStore) {
        this.dataStore = dataStore;
    }
 
    @Post
    new(request) {
        if (request.query.exists("id")) {
            const key = request.query.get("id");
            return {
                key: this.dataStore.get(key)
            };
        }

        return [this.dataStore];
    }

    @Get
    @Cache(10)
    retrieve(request) {
        if (request.query.exists("id")) {
            const key = request.query.get("id");
            return {
                key: this.dataStore.get(key)
            };
        }

        return [this.dataStore];
    }

    @Get
    @Path("/last")
    last(request) {
        const keys = this.dataStore.keys();
        const idx = this.dataStore.len()-1;
        const lastKey = keys[idx];

        return JsonResponse({lastKey: this.dataStore.get(lastKey)});
    }
}

print(Releases.methodAnnotations);
```

Results:

```js
{"new": {"Post": nil}, "retrieve": {"Cache": 10, "Get": nil}, "__annotatedMethodName": {"Path": "/last", "Get": nil}}
```

**Comment by Jason2605** [comment]
I think it may actually be to do with dictDelete. Removing that call seems to have all the methods along with the placeholder

**Comment by Jason2605** [comment]
Okay yeah, it's the dictSet. The robinhood hashing is moving entries about so `entry->key` now points at something else. Should be resolvable
