### ISSUE TITLE
[FEATURE] - Add Dictu to Github Linguist

### ISSUE THREAD

**Issue by briandowns** [dictu-lang/Dictu#601]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Looks like we can PR against https://github.com/github/linguist and add the ability for Github to assign a color to the language and have it parse Dictu files and add syntax highlighting. 

Is this something you'd (@Jason2605 ) want done? If so, I can get the PR going.

**Comment by Jason2605** [comment]
It is for sure but the realist in myself thinks we won’t be anywhere near the 200 unique user / repos on GitHub requirement for it unfortunately

**Comment by briandowns** [comment]
Good point. Will close for now and reopen when we're closer to meeting those expectations.
