### ISSUE TITLE
[FEATURE] - Class Field Annotations

### ISSUE THREAD

**Issue by briandowns** [dictu-lang/Dictu#623]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

It'd be really helpful for a few different projects I'm working on to have field level annotations.

An example: 

```js
abstract class Model {

    @PrimaryKey
    @AutoIncrement
    var id = 0;

    @Type("TIMESTAMP")
    var createdAt = "";

    @Type("TIMESTAMP")
    var updatedAt = "";

    @Type("TIMESTAMP")
    var deletedAt = "";

    // used for processing
    var usingModel = true;
}
```

### Describe alternatives you've considered

N/A

**Comment by Jason2605** [comment]
I have a branch on `feature/attributeAnnotations` that should have this in place now if you want to check it out. Need to write some tests and some docs for it but the functionality should be in place. Will work the same as the other annotations except it is exposed on `attributeAnnotations` (potentially going to change this)

**Comment by briandowns** [comment]
That's awesome! Happy to check it out and do some testing.

**Comment by Jason2605** [comment]
Nice one, thank you! Out of curiosity what are you making? Some kind of ORM?

**Comment by briandowns** [comment]
No prob. As for what I'm making, exactly, a very simple, albeit, naive ORM. Should be interesting.

**Comment by Jason2605** [comment]
That sounds really cool! Hopefully the feature branch works for you then
