### ISSUE TITLE
[FEATURE] - Add the Ability to Hash an Object

### ISSUE THREAD

**Issue by briandowns** [dictu-lang/Dictu#624]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

It'd be helpful to have the ability to derive a hash value of an object similar to calling hash on a Java object.

**Comment by Jason2605** [comment]
This one should be fairly straight forward with Value types just actually being a number, will get on this 👍

**Comment by briandowns** [comment]
Sounds good! I’m happy to do this one as well if you’re busy.

**Comment by Jason2605** [comment]
Go for it, thank you!

**Comment by briandowns** [comment]
What were your thoughts around approach?

**Comment by Jason2605** [comment]
I would stick a new .hash in the Object module that just returns Value as a number

**Comment by Jason2605** [comment]
Actually on a longer think, this may be a lot more tricky than first anticipated

**Comment by briandowns** [comment]
Thanks for updating so quickly! I've done a few different things so far with varied results. I'll mess around a bit more and update the WIP PR I have up.

**Comment by Jason2605** [comment]
#625
