### ISSUE TITLE
[BUG] - Unable to Create class, var, or const with the Name "C"

### ISSUE THREAD

**Issue by briandowns** [dictu-lang/Dictu#637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I ran into an issue while testing other code when I tried to create a class named "C". I think it's conflicting with the internal module of the same name. I tested with const's and var's and it's the same behavior.

### Steps To Reproduce

Using the latest version:

```sh
>>> class C {}
>>> const c = C();
Error: File 'repl', line 1
       'module' is not callable
```

```sh
>>> const C = 90;
>>> print(C);
<Module C>
>>> var C = 90;
>>> print(C);
<Module C>
```

**Comment by briandowns** [comment]
I adjusted the code to not auto load the C module but to require it be explicitly imported, tested, and seemed to work fine. I can push a PR but wanted to get your (@Jason2605) thoughts and feedback on the matter before I did.

**Comment by Jason2605** [comment]
Please yeah, I'm unsure the reason I didn't autoload that module
