### ISSUE TITLE
[BUG] Seems to be a slight memory issue

### ISSUE THREAD

**Issue by Jason2605** [dictu-lang/Dictu#666]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
import HTTP;

class Weather {
    const API_URL = 'http://api.weatherapi.com/v1';

    init (private apiKey) {}

    getCurrentWeather() {
        const response = HTTP.get(
            "{}/current.json?key={}&q=London&aqi=no".format(Weather.API_URL, this.apiKey)
        ).unwrap();

        const data = response.json().unwrap()["current"];

        return {
            "temp": data["temp_c"],
            "condition": data["condition"]["text"],
        };
    }
    getTodaysForcast() {
        const response = HTTP.get(
            "{}/forecast.json?key={}&q=London&aqi=no&days=1".format(Weather.API_URL, this.apiKey)
        ).unwrap();

        return response.content;
    }
}

print(Weather("key").getTodaysForcast());

// Total bytes lost: 1
```

**Comment by briandowns** [comment]
How did you make that determination? I'm curious for my own future troubleshooting knowledge.

**Comment by Jason2605** [comment]
Issue is a bit bare sorry, I need to put more info onto these things. As for determination do you mean the amount of bytes lost? If so, build Dictu in debug mode and it'll display that message after you run the script.

The issue itself is on large HTTP responses and having to resize the string from a little look into it

**Comment by briandowns** [comment]
Awesome. That's what I was curious about. Thanks!
