### ISSUE TITLE
[FEATURE] - Ability to Print Output without New Line Character

### ISSUE THREAD

**Issue by briandowns** [dictu-lang/Dictu#679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

It'd be nice to be able to print output without the added newline character. 

### Describe alternatives you've considered

1. Change the implementation of print to not include the new line character but that potentially breaks or impacts any application currently using `print`.
2. Introduce new module that has print and println, etc functions to achieve this.
3. Open to suggestions

**Comment by Jason2605** [comment]
Yeah this is an interesting one. Ideally we could do something like Python where you can pass a kwarg (allowing the public API to stay the same)

```
print(...values, end="\n");
```

**Comment by briandowns** [comment]
I think I'm in favor of an `IO` module than messing with the builtin `print`. If that's ok, I can get a PR up in a few days.

**Comment by Jason2605** [comment]
Sounds good to me! Thank you
