### ISSUE TITLE
[FEATURE] Pretty Print

### ISSUE THREAD

**Issue by Jason2605** [dictu-lang/Dictu#682]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Extend the new IO module to allow us to pretty print different datatypes

### Describe the solution you'd like

We could actually just piggy back off of the JSON module as this allows us to "stringify" values with a given indentation level

**Comment by briandowns** [comment]
I think it might go better in the Object package.

**Comment by Jason2605** [comment]
Fair point, I’d probably agree

**Comment by briandowns** [comment]
Do we want the user to be able to specify the indentation like they can with the JSON module?

**Comment by Jason2605** [comment]
It would be nice to have yeah!

**Comment by briandowns** [comment]
PR coming shortly then.
