### ISSUE TITLE
[FEATURE] Add Ability for Annotations to Take More Than Strings

### ISSUE THREAD

**Issue by briandowns** [dictu-lang/Dictu#685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I'm finding more use cases to have the ability to pass more than strings to annotations.

### Describe the solution you'd like

It'd be great for annotations to be able to take all primitive types.

Examples:

```cs
@Config({"concurrency": 10})
class App {
    init() {}
}
```

```cs
@Memoize(8)
def f() {}
```

**Comment by Jason2605** [comment]
Annotations should currently allow for strings, numbers, boolean and nil - as for more complex types such as dicts / lists etc we could look into it but would still need to make sure the keys and values are made up from literal values as these are generated at compile time

A workaround is to `@Config('{"concurrency": 10}')` and JSON parse it (not great, but it's at least something for now)

**Comment by briandowns** [comment]
I can't believe I forgot that it takes those basic types. Right. So the JSON solution will work for now. Thanks for that idea!

**Comment by Jason2605** [comment]
Haha no worries! I've got something coming together extending it so we can allow more types can see the WIP [here](https://github.com/dictu-lang/Dictu/tree/feature/annotations)

**Comment by briandowns** [comment]
Oh wow, super cool. This will make some of the features in Wanbli a lot easier to implement. Crazy how fast you get some of this stuff pumped out.

**Comment by Jason2605** [comment]
Haha cheers man, we've both got a good rhythm going on this, I'm enjoying it! I'll hopefully be able to get most of it finished off tomorrow for you

**Comment by Jason2605** [comment]
I think that should be it working now

**Comment by briandowns** [comment]
Absolute legend!
