### ISSUE TITLE
[FEATURE] Move history.txt

### ISSUE THREAD

**Issue by Jason2605** [dictu-lang/Dictu#712]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

We probably want to move the `history.txt` that gets created to next to the installed interpreter location, this will 1) stop history.txt polluting every directory it enters and 2) allow history to be saved regardless of terminal location

**Comment by briandowns** [comment]
One more thought. The home dir can be default and maybe an ENV var to override it?

**Comment by Jason2605** [comment]
I like it yeah, potentially `DICTU_PATH`?

**Comment by briandowns** [comment]
Sounds good to me!

**Comment by briandowns** [comment]
I'm happy to take this if you haven't started working on it yet.
