### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by functionalmethod** [dictu-lang/Dictu#714]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Install (any method), failure message after the first CMAKE command: `CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
`

### Expected Behavior

Install properly

### Steps To Reproduce

Follow `read.me` steps.

### Anything else?

I have checked my CMAKE

**Comment by Jason2605** [comment]
Can you paste the full output you get please?

Also which version of cmake are you running / which compiler (and version) are you also trying to use?

**Comment by functionalmethod** [comment]
CMAKE 3.28.1 and the full error is listed above; Same problem on a windows machine

**Comment by Jason2605** [comment]
Which compiler are you attempting to use?

Which version of make (not cmake) do you have?

**Comment by functionalmethod** [comment]
I tried to run the process with each compiler (each time completely restarting/ deleting folder and everything). I don't know which version of make?

**Comment by Jason2605** [comment]
If CMake is generating make files you will need make installed

**Comment by functionalmethod** [comment]
thanks
