### ISSUE TITLE
[FEATURE] Finer Granularity with System.sleep

### ISSUE THREAD

**Issue by briandowns** [dictu-lang/Dictu#721]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

I'd like the ability to access usleep or have millisecond stops available. I wanted to get your (@Jason2605) feedback on how you'd think that'd be best implemented. I looked at the code for sleep and I can change it but I'm a bit hesitant to break the API. I was considering adding another function called usleep that functions exactly the same as the underlying implementation.

**Comment by briandowns** [comment]
Oooorrrrrr.... I can pass in the value of 1 divided by some value. Nevermind. Enjoy your holiday. :D

**Comment by Jason2605** [comment]
Yeah the sleep should allow for values < 1 and in decimal formats. You too mate, have a nice Christmas and new year!!
