### ISSUE TITLE
[FEATURE] list methods should support negative index

### ISSUE THREAD

**Issue by haifenghuang** [dictu-lang/Dictu#740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

Since the list support negative index, so In `lists.c` file, `insertListItem` and `popListItem` should also support negative index. Take `insertListItem` as an example:

```c
    int index = AS_NUMBER(args[2]);

    if (index < 0 || index > list->values.count) {
        runtimeError(vm, "Index passed to insert() is out of bounds for the list given");
        return EMPTY_VAL;
    }
```

### Describe the solution you'd like

It should be like below:
```c
    int index = AS_NUMBER(args[2]);
    if (index < 0) index = list->values.count + index; // allow negative indexes   
    if (index < 0 || index > list->values.count) {
        runtimeError(vm, "Index passed to insert() is out of bounds for the list given");
        return EMPTY_VAL;
    }
```

**Comment by Jason2605** [comment]
Valid comment, happy for you to PR this mate!
